data:
  waveform_dataset_path: /data/fs201368/tp41139/waveforms/waveform_dataset_T8_imbh.hdf5  # Contains intrinsic waveforms
  train_fraction: 0.95
  domain_update:
    f_min: 6.0
    f_max: 256.0
  svd_size_update: 400  # Optionally, reduce the SVD size when decompressing (for performance)
  detectors:
    - ET-1
    - ET-2
    - ET-3
  extrinsic_prior:  # Sampled at train time
    dec: default
    ra: default
    geocent_time: bilby.core.prior.Uniform(minimum=-0.10, maximum=0.10, name='geocent_time')
    psi: default
    luminosity_distance: bilby.core.prior.LogUniform(minimum=1000.0, maximum=100_000.0, name='luminosity_distance')
  ref_time: 1126259462.391
  inference_parameters:
  - chirp_mass
  - mass_ratio
  - chi_1
  - chi_2
  - theta_jn
  - dec
  - ra
  - geocent_time
  - luminosity_distance
  - psi
  # Uncomment the snippet below to apply random frequency crops. The resulting Dingo
  # model will be able to perform inference with variable frequency ranges.
#  random_strain_cropping:
#    f_min_upper: 32
#    f_max_lower: 512
#    cropping_probability: 0.8

     



model:
  posterior_model_type: normalizing_flow
  # kwargs for neural spline flow
  posterior_kwargs:
    num_flow_steps: 30
    base_transform_kwargs:
      hidden_dim: 1024
      num_transform_blocks: 5
      activation: elu
      dropout_probability: 0.0
      batch_norm: True
      num_bins: 8
      base_transform_type: rq-coupling
  # kwargs for embedding net
  embedding_kwargs:
    output_dim: 256
    hidden_dims: [1024, 1024, 1024, 1024, 1024, 1024,
                  1024, 1024, 1024, 1024, 1024, 1024,
                  512, 512, 512, 512, 512, 512,
                  512, 512, 512, 512, 512, 512,
                  256, 256, 256, 256, 256, 256]
    activation: elu
    dropout: 0.0
    batch_norm: True
    svd:
      num_training_samples: 50000
      num_validation_samples: 2000
      size: 400

training:
  stage_0:
    epochs: 50
    asd_dataset_path: training_data/asds_ET_T8.hdf5 # this should just contain a single fiducial ASD per detector for pretraining
    freeze_rb_layer: True
    optimizer:
      type: adam
      lr: 7.0e-5
    scheduler:
      type: cosine
      T_max: 50
    batch_size: 8192


# Local settings for training that have no impact on the final trained network.
local:
  device: cuda # Change this to 'cuda' for training on a GPU.
  num_workers: 12  # num_workers >0 does not work on Mac, see https://stackoverflow.com/questions/64772335/pytorch-w-parallelnative-cpp206
  runtime_limits:
    max_time_per_run: 3600000
    max_epochs_per_run: 500
  checkpoint_epochs: 50
  leave_waveforms_on_disk: True
  # local_cache_path: tmp # uncomment to avoid slow data loading during training due to network traffic on cluster
 
