################################################################################
##  Job submission arguments
################################################################################

local = True
# accounting = ligo.dev.o4.cbc.pe.dingo
request-cpus-importance-sampling = 48
n-parallel = 4
sampling-requirements = [TARGET.CUDAGlobalMemoryMb>20000]
extra-lines = [+WantsGPUNode = True]
simple-submission = false

################################################################################
##  Sampler arguments
################################################################################

model = /scratch/tpausch/models/imbh_200_T2/model_latest.pt
device = 'cuda'
num-samples = 50000
batch-size = 10000
recover-log-prob = true
importance-sample = true

################################################################################
## Data generation arguments
################################################################################

trigger-time = 1126259462.391          # = ref_time from train_settings.yaml
label = imbh_T2_injection_test
outdir = outdir_imbh_T2_test
detectors = [ET-1, ET-2, ET-3]
duration = 2.0                          # = 1 / delta_f (0.5) from domain settings
sampling-frequency = 512.0              # >= 2 * f_max (256.0)
gaussian-noise = True                  # no real ET data -> simulate noise from psd-dict
psd-dict = {ET-1: ET_ASD_10km.txt, ET-2: ET_ASD_10km.txt, ET-3: ET_ASD_10km.txt}




################################################################################
## Injection arguments
################################################################################
injection = True
dingo_injection=True
injection_dict = {
    chirp_mass=175.0,
    mass_ratio=0.5,
    chi_1=0.0,
    chi_2=0.0,
    luminosity_distance=50000.0,
    theta_jn=1.4,
    psi=1.4,
    phase=1.3,
    geocent_time=1126259462.391,
    ra=1.375,
    dec=-1.2108,
}
injection-file=None
injection-numbers=None
injection-waveform-approximant=IMRPhenomXPHM
injection-frequency-domain-source-model=None
injection-waveform-arguments=None
injection-waveform-generator-constructor-dict=None


################################################################################
## Plotting arguments
################################################################################

plot-corner = true
plot-weights = true
plot-log-probs = true

calibration-correction-type = {ET-1: data, ET-2: data, ET-3: data}